"""Fill docs/STORYBOARD.md (drafted by the engine) with the director's rows, in scene order."""
import re
R = [
# (on screen, purpose, how it leaves, what carries)
("Title. Black, then in the first second a low fast glide over a river at golden hour, mist on the water, reeds and trees rushing past; the camera rises and the garden of Delight opens ahead: hills of orchards, four rivers shining, a huge tree on a rise in the far centre. GENESIS 3 / THE EXILE sets in tall light capitals and dissolves into the haze.",
 "Paradise is real and we are in it; the first second is already moving.", "The camera keeps rising into a wide over the meadow.", "Gold light, the river, the tree on the rise far off."),
("Wide golden meadow by the river, tall grass and wildflowers in wind; a flock of birds wheels low across the frame and settles; deer-like shapes far off in haze; the light is generous and warm.",
 "The creatures the Lord God formed: the good creation before the fall.", "Push toward a tree at the meadow's edge; a branch fills the right of frame.", "The branch, the gold light."),
("Macro: the serpent slides along a sunlit branch, iridescent green-gold scales, rack focus from its moving coils to its head and still eye.",
 "Meet the serpent: beautiful and wrong.", "The head lifts and turns off frame left.", "The turn of the head."),
("Over the serpent's head (soft, close, in the foreground) to a distant woman's silhouette, backlit gold in tall grass below the trees; focus pulls from the head to her.",
 "The serpent chooses the woman; she is innocent and far off.", "Focus stays on her as the light flares.", "Her direction; the orchard behind her."),
("A slow lateral glide down an orchard row, every tree heavy with fruit (figs, pomegranates, golden apples), the camera low, sun strobing through branches.",
 "The serpent's question twists abundance into restriction.", "The row ends in bright haze.", "Fruit everywhere."),
("Close and generous: fruit hanging in light, dew, bees; a fig splits ripe on a branch; leaves turn in the breeze.",
 "The woman answers: we eat freely.", "Rack focus deeper into the orchard.", "Layers of trees in haze."),
("From inside the orchard canopy, rising: the trees spread out over rolling hills, the rivers between them, all of it given.",
 "Throughout the garden: the whole gift.", "The camera crests the canopy; the tree on the rise comes into view.", "The tree at the centre."),
("The tree at the centre: alone on a rise in a clearing, immense, darker leaves, a few red fruit catching the sun; the rivers part around its hill; the camera holds at a respectful distance.",
 "The one barred tree.", "Push in toward its lower branches.", "A single red fruit."),
("A single red fruit at medium distance, partly hidden by leaves, in cooler side light; the camera drifts sideways and the focus slides off the fruit as the leaves shiver on 'touch'.",
 "The command is gentle and clear: not even to touch it.", "The light dims a stop.", "The fruit, the stillness."),
("The tree's shadow sweeps across the grass as a cloud crosses the sun; one fruit in silhouette; everything goes still for a beat.",
 "'Lest we die': the weight of it.", "Hard cut to the serpent.", "Darkness at the trunk."),
("The serpent pours down the trunk of the tree toward camera, coils catching the light, its head arriving into close-up.",
 "The serpent answers.", "Its tongue flicks; the eye fills the frame.", "The eye."),
("Extreme close-up of the serpent's eye: a slit pupil, and in its glassy surface the reflected red fruit and the gold sky.",
 "The lie: no death.", "The reflection blooms to white.", "Glare into light."),
("Under the tree looking up: shafts of sun through dark leaves, the red fruit glowing, slow orbit, a lens flare; seductive and beautiful.",
 "The promise: eyes awake.", "The orbit settles on the canopy's dark side.", "Half light, half shadow."),
("The tree reflected upside down in a mirror-still pool beneath it: above gold, below dark; a fruit falls past the camera, the reflection ripples and splits into two trees, one lit, one black.",
 "Good and evil: knowledge as division.", "The ripples run to the frame edge.", "The ripple, the wind rising."),
("Instrumental surge: wind slams across the garden, the canopy thrashes, grass flattens in waves, petals and leaves stream past the lens, the sun strobes through the moving leaves; quick handheld energy on the drums.",
 "The guitars surge: the moment turns.", "Wind drops; the camera is under the branches.", "The branches, the fruit."),
("Her point of view: looking up into the branches, fruit glowing among leaves, the frame drifting closer.",
 "She saw it was good for food.", "The focus finds one fruit.", "The fruit in focus."),
("Macro, shallow focus: the fruit turns slowly on its stem, dew running down its skin, bokeh of gold behind; the most beautiful image in the film.",
 "Beauty before her eyes: desire.", "A hard snap.", "The stem."),
("The branch snaps up as the fruit is torn away (we see only the branch); leaves shower; the empty stem drips.",
 "She plucked and ate: the act, unseen.", "Leaves fall past the lens.", "Falling leaves."),
("Two silhouettes stand close against the low sun under the tree, far away and small; a bitten fruit drops into the grass in the foreground and lies there, its flesh already browning.",
 "He ate as well.", "The light starts to go cold.", "The bitten fruit."),
("The grade drains from gold to cold blue-grey across the shot: the same garden, suddenly exposed; wind dies; a wide, empty, uncomfortable composition.",
 "Their eyes open: shame.", "Push into dense foliage.", "Big fig leaves."),
("Macro: large fig leaves in cold light, overlapping, stitched with green fibre; the leaves curl closed.",
 "The fig leaves: covering.", "The leaves tremble as a breeze arrives.", "The breeze."),
("Late afternoon: a breeze moves through the garden toward the camera, grass parting in a long wave, leaves turning silver, a warm light rising behind the trees.",
 "They hear His voice: the cool of the day.", "The light moves.", "Moving light."),
("A soft column of light walks through the trees toward the camera; leaves turn to it as it passes, the grass bows; no figure, only presence.",
 "The Lord God walking in the garden.", "The light passes behind trunks.", "Trunks, shadows."),
("Among dark trunks two silhouettes turn and slip away from the light into the trees; their shadows stretch long.",
 "They turn from His face.", "Darkness closes between the trunks.", "The thicket."),
("Deep in a thicket: the camera slides slowly between trunks and leaves; through a gap, the searching light passes on the far side; they are hidden somewhere near us.",
 "Hiding from God (a held breath; the music is near silent).", "The light finds the gap.", "Light through the gap."),
("Dusk over the garden canopy, the camera rising; light floods across the treetops as the call goes out; the word ADAM in tall warm capitals.",
 "God calls: 'Adam, where are you?' (not because He does not know).", "The light hangs over the canopy.", "Leaves below."),
("Inside the leaves looking out: trembling foliage in the foreground, the warm light beyond; breath-like movement.",
 "Adam's answer: afraid, naked, hid.", "The leaves part a little.", "The light."),
("Close on a cold, still pool at dusk; the surface shows only darkness and one star of light; a drop falls.",
 "'Who told you?': the question that knows.", "The ripple spreads.", "The tree."),
("The tree at dusk, cold; the camera rises to the broken stem where the fruit was taken, a dark wound in the branch.",
 "The question names the tree.", "The camera turns away from the branch.", "Two figures."),
("Two silhouettes on cold grass, standing apart, a widening gap between their long shadows; the man's shadow turns toward the woman.",
 "The blame: 'the woman You gave'.", "Wind between them.", "The woman's shadow."),
("Close: the woman's silhouette in cold rim light, head bowed, among dark leaves.",
 "God asks the woman: 'What have you done?'", "She turns toward the grass.", "The grass."),
("Low in the grass: the serpent slides away fast, leaving a trail through the dew.",
 "'The serpent tricked me.'", "It disappears under the leaves.", "Darkening sky."),
("The sky above the garden darkens as storm clouds pile up; first wind.",
 "God turns to the serpent.", "Lightning builds.", "The storm."),
("The storm breaks over Paradise: lightning flashes over the tree on its rise, rain sweeps across, the serpent coiled on a branch lit by the flashes.",
 "The curse falls on the serpent.", "A flash whites out.", "Rain, earth."),
("Wide plain in the storm: dark animal herds and birds scatter under the lightning, tiny against the land.",
 "Above every beast of the earth.", "Down to the ground.", "Mud, dust."),
("Low macro on the ground: the serpent, no longer gleaming, drags its belly across dry dust; its scales dulled.",
 "On your belly you shall go.", "Dust lifts behind it.", "Dust."),
("Dust in the serpent's mouth; it moves through a field of dry cracked earth to the horizon; dust devils.",
 "Dust you shall eat all your days.", "The ground cracks open.", "The crack."),
("A crack runs across the earth between two lights, one warm, one cold; it widens slowly.",
 "Enmity between the serpent and the woman, its seed and hers.", "The warm light grows.", "Warm light."),
("A pillar of light stands over the serpent's head on the dark ground; the serpent rears and strikes only at its foot; the light does not move.",
 "The promise: He will watch against your head (the Saviour).", "The light brightens to fill the frame.", "Rain."),
("Rain on dark earth at dusk; a seed in the soil splits and a green shoot pushes up through the mud, painfully, slowly.",
 "In pain you shall bring forth children: life through pain.", "The shoot opens.", "The shoot, the ground."),
("Close, physical: in storm light at a ridge's edge, one thing closes over another (hands, or a vine binding a young plant), then a rack focus to the storm.",
 "Your husband shall rule over you: the broken order.", "Wind sweeps the ridge.", "The land."),
("The tree on its rise under a black sky, lightning behind it; the camera pulls back from it.",
 "God speaks to Adam: you ate from the tree.", "The ground in front comes up.", "The soil."),
("Time-lapse: lush soil turns to cracked hardpan; grass withers and blows away; the sun goes white.",
 "Cursed is the earth in your work.", "Heat haze.", "Dry ground."),
("Thorn branches grow and twist up out of the dry ground in time-lapse; thistle heads open, silver and sharp, in hard light.",
 "Thorns and thistles.", "Close on a thorn.", "The heat."),
("A single drop of sweat falls in slow motion and splashes into dry dust.",
 "In the sweat of your face.", "The dust settles.", "Dust."),
("A figure of earth, a man-shaped form of packed clay and sand, stands in the hot wind; grains stream off it.",
 "Till you go back to the earth; you are earth.", "The wind strengthens.", "Grains flying."),
("The form crumbles and blows away into dust; the dust drifts across an empty plain.",
 "To earth you will return.", "Dust clears into a warmer light.", "Warm light."),
("A field at first light: flowers open in time-lapse across a hillside, dew lit gold; the word LIFE glows.",
 "Eve is named Life: mother of all the living.", "The light rises.", "Warmth."),
("Two warm-rimmed silhouettes in warm, sourceless dusk light; on 'and clothed them' a soft garment of skin settles around one figure's shoulders as if laid by an unseen hand.",
 "God clothes them: mercy.", "Sparks rise into the night.", "The night sky."),
("Across a river at dusk, far off on the other side of the garden, the tree of life: white-gold light in its leaves.",
 "God speaks: man now knows good and evil.", "Push across the water.", "The tree of life."),
("The camera reaches toward the tree of life across the river, and is held back; the light ahead brightens.",
 "Lest he reach.", "Continue toward the tree.", "The light of the tree."),
("The tree of life close: leaves of light, fruit like lamps, slow orbit; it is out of reach.",
 "The tree of life, and living forever.", "The camera pulls back fast.", "The garden's edge."),
("Pulling back out of the garden through a great gate of trees and rock at night; the garden glows behind.",
 "So God sent him out.", "Through the gate.", "The barren land."),
("Outside: a barren plain at night, a lone silhouette walks away from the garden's glow toward dark land.",
 "To work the ground he was taken from.", "Wide.", "The figure."),
("Wide: a small campfire on the plain far from the garden, whose glow is visible across the valley.",
 "Settled across from Delight.", "Push toward the gate.", "The gate."),
("At the gate: towering cherubim of wing and flame, wings layered with suggested eyes, unfolding; the camera drops between them as the turning sword of fire ignites on 'turning', a wheel of flame streaming sparks, then rises over the flame.",
 "He stationed cherubim and the turning sword of fire: one image, as Genesis gives it.", "The camera rises over the flame.", "The path."),
("The path between the cherubim, running into the garden toward the tree of life far away; on the last note a single small star rises above the far horizon; long hold to the end of the song.",
 "The way to the tree of life is guarded, not destroyed: the ending is unresolved, but the star is the promise.", "Fade to black with the last sound.", "Silence."),
]
p = 'docs/STORYBOARD.md'
s = open(p).read()
rows = [l for l in s.splitlines() if l.startswith('| ') and 'TODO' in l]
assert len(rows) == len(R), (len(rows), len(R))
for l, (a, b, c, d) in zip(rows, R):
    cells = [x.strip() for x in l.strip().strip('|').split('|')]
    on = cells[1].replace('TODO', a) if cells[1] != 'TODO' else a
    new = f"| {cells[0]} | {on} | {b} | {c} | {d} |"
    s = s.replace(l, new, 1)
open(p, 'w').write(s)
